[package]
name = "logging"
version = "0.0.1"
edition = "2024"

[dependencies]
configs = { git = "ssh://git@github.com/ruskit/configs.git", rev = "v0.0.0" }

tracing-bunyan-formatter = { version = "0.3.10" }
tracing-subscriber = { version = "0.3.19" }
tracing-log = { version = "0.2.0" }
tracing = { version = "0.1.41" }
thiserror = { version = "2.0.12" }